### ISSUE TITLE
Android13的手机， 使用4g，会出现异常

### ISSUE THREAD

**Issue by yang1256149685** [LiteAVSDK/TRTC_Android#17]
getNetworkType会使用phone_state权限，目前这块在android13的系统上被限制了，这个需要优化解决一下嘞

java.lang.SecurityException: getDataNetworkTypeForSubscriber
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8593)
	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3090)
	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3054)
	at com.tencent.liteav.basic.datareport.TXCDRApi.getNetworkType(TXCDRApi.java:313)
	at com.tencent.liteav.basic.datareport.TXCDRApi.setCommonInfo(TXCDRApi.java:116)
	at com.tencent.liteav.basic.datareport.TXCDRApi.txReportDAU(TXCDRApi.java:80)
	at com.tencent.liteav.beauty.a.a(ReportDuaManage.java:96)
	at com.tencent.liteav.beauty.c.<init>(TXCVideoPreprocessor.java:257)
	at com.tencent.liteav.c.<init>(TXCCaptureAndEnc.java:154)
	at com.tencent.liteav.trtc.impl.TRTCCloudImpl.<init>(TRTCCloudImpl.java:239)
	at com.tencent.liteav.trtc.impl.TRTCCloudImpl.sharedInstance(TRTCCloudImpl.java:198)
	at com.tencent.trtc.TRTCCloud.sharedInstance(TRTCCloud.java:39)
	at com.elong.android.flutter.plugins.TRTCPlugin.onMethodCall(TRTCPlugin.java:99)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:341)
	at android.os.Looper.loopOnce(Looper.java:168)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by rankezhang** [comment]
我也遇到这个问题了，兄弟升级 SDK 能解决么？否则申请 phone_state 可能会导致应用商店被下架

**Comment by yang1256149685** [comment]
升级解决了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月18日(星期一) 晚上7:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LiteAVSDK/TRTC_Android] Android13的手机， 使用4g，会出现异常 (Issue #17)





 
我也遇到这个问题了，兄弟升级 SDK 能解决么？否则申请 phone_state 可能会导致应用商店被下架
